# CMake generated Testfile for 
# Source directory: E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test
# Build directory: E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_0 "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_0")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_0 "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_0")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_0 "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_0")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_0 "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_0")
ELSE()
  ADD_TEST(bsdcpio_test_0 NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_basic "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_basic")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_basic "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_basic")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_basic "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_basic")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_basic "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_basic")
ELSE()
  ADD_TEST(bsdcpio_test_basic NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_cmdline "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_cmdline")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_cmdline "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_cmdline")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_cmdline "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_cmdline")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_cmdline "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_cmdline")
ELSE()
  ADD_TEST(bsdcpio_test_cmdline NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_format_newc "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_format_newc")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_format_newc "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_format_newc")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_format_newc "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_format_newc")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_format_newc "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_format_newc")
ELSE()
  ADD_TEST(bsdcpio_test_format_newc NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_gcpio_compat "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_gcpio_compat")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_gcpio_compat "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_gcpio_compat")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_gcpio_compat "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_gcpio_compat")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_gcpio_compat "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_gcpio_compat")
ELSE()
  ADD_TEST(bsdcpio_test_gcpio_compat NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_0 "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_0")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_0 "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_0")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_0 "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_0")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_0 "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_0")
ELSE()
  ADD_TEST(bsdcpio_test_option_0 NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_B_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_B_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_B_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_B_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_B_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_B_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_B_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_B_upper")
ELSE()
  ADD_TEST(bsdcpio_test_option_B_upper NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_C_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_C_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_C_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_C_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_C_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_C_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_C_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_C_upper")
ELSE()
  ADD_TEST(bsdcpio_test_option_C_upper NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_J_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_J_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_J_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_J_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_J_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_J_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_J_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_J_upper")
ELSE()
  ADD_TEST(bsdcpio_test_option_J_upper NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_L_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_L_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_L_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_L_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_L_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_L_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_L_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_L_upper")
ELSE()
  ADD_TEST(bsdcpio_test_option_L_upper NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_Z_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_Z_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_Z_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_Z_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_Z_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_Z_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_Z_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_Z_upper")
ELSE()
  ADD_TEST(bsdcpio_test_option_Z_upper NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_a "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_a")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_a "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_a")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_a "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_a")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_a "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_a")
ELSE()
  ADD_TEST(bsdcpio_test_option_a NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_c "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_c")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_c "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_c")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_c "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_c")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_c "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_c")
ELSE()
  ADD_TEST(bsdcpio_test_option_c NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_d "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_d")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_d "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_d")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_d "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_d")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_d "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_d")
ELSE()
  ADD_TEST(bsdcpio_test_option_d NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_f "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_f")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_f "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_f")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_f "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_f")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_f "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_f")
ELSE()
  ADD_TEST(bsdcpio_test_option_f NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_help "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_help")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_help "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_help")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_help "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_help")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_help "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_help")
ELSE()
  ADD_TEST(bsdcpio_test_option_help NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_l "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_l")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_l "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_l")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_l "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_l")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_l "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_l")
ELSE()
  ADD_TEST(bsdcpio_test_option_l NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_lzma "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_lzma")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_lzma "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_lzma")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_lzma "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_lzma")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_lzma "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_lzma")
ELSE()
  ADD_TEST(bsdcpio_test_option_lzma NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_m "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_m")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_m "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_m")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_m "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_m")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_m "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_m")
ELSE()
  ADD_TEST(bsdcpio_test_option_m NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_t "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_t")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_t "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_t")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_t "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_t")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_t "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_t")
ELSE()
  ADD_TEST(bsdcpio_test_option_t NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_u "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_u")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_u "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_u")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_u "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_u")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_u "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_u")
ELSE()
  ADD_TEST(bsdcpio_test_option_u NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_version "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_version")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_version "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_version")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_version "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_version")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_version "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_version")
ELSE()
  ADD_TEST(bsdcpio_test_option_version NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_y "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_y")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_y "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_y")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_y "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_y")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_y "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_y")
ELSE()
  ADD_TEST(bsdcpio_test_option_y NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_option_z "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_z")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_option_z "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_z")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_option_z "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_z")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_option_z "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_option_z")
ELSE()
  ADD_TEST(bsdcpio_test_option_z NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_owner_parse "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_owner_parse")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_owner_parse "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_owner_parse")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_owner_parse "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_owner_parse")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_owner_parse "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_owner_parse")
ELSE()
  ADD_TEST(bsdcpio_test_owner_parse NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_passthrough_dotdot "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_passthrough_dotdot")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_passthrough_dotdot "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_passthrough_dotdot")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_passthrough_dotdot "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_passthrough_dotdot")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_passthrough_dotdot "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_passthrough_dotdot")
ELSE()
  ADD_TEST(bsdcpio_test_passthrough_dotdot NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdcpio_test_passthrough_reverse "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_passthrough_reverse")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdcpio_test_passthrough_reverse "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_passthrough_reverse")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdcpio_test_passthrough_reverse "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_passthrough_reverse")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdcpio_test_passthrough_reverse "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdcpio.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/cpio/test" "test_passthrough_reverse")
ELSE()
  ADD_TEST(bsdcpio_test_passthrough_reverse NOT_AVAILABLE)
ENDIF()
