# CMake generated Testfile for 
# Source directory: E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test
# Build directory: E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test
# 
# This file includes the relevent testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_0 "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_0")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_0 "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_0")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_0 "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_0")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_0 "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_0")
ELSE()
  ADD_TEST(bsdtar_test_0 NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_basic "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_basic")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_basic "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_basic")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_basic "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_basic")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_basic "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_basic")
ELSE()
  ADD_TEST(bsdtar_test_basic NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_copy "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_copy")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_copy "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_copy")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_copy "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_copy")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_copy "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_copy")
ELSE()
  ADD_TEST(bsdtar_test_copy NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_empty_mtree "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_empty_mtree")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_empty_mtree "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_empty_mtree")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_empty_mtree "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_empty_mtree")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_empty_mtree "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_empty_mtree")
ELSE()
  ADD_TEST(bsdtar_test_empty_mtree NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_format_newc "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_format_newc")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_format_newc "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_format_newc")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_format_newc "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_format_newc")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_format_newc "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_format_newc")
ELSE()
  ADD_TEST(bsdtar_test_format_newc NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_help "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_help")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_help "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_help")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_help "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_help")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_help "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_help")
ELSE()
  ADD_TEST(bsdtar_test_help NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_C_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_C_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_C_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_C_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_C_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_C_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_C_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_C_upper")
ELSE()
  ADD_TEST(bsdtar_test_option_C_upper NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_H_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_H_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_H_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_H_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_H_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_H_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_H_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_H_upper")
ELSE()
  ADD_TEST(bsdtar_test_option_H_upper NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_L_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_L_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_L_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_L_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_L_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_L_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_L_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_L_upper")
ELSE()
  ADD_TEST(bsdtar_test_option_L_upper NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_O_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_O_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_O_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_O_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_O_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_O_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_O_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_O_upper")
ELSE()
  ADD_TEST(bsdtar_test_option_O_upper NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_T_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_T_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_T_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_T_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_T_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_T_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_T_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_T_upper")
ELSE()
  ADD_TEST(bsdtar_test_option_T_upper NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_U_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_U_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_U_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_U_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_U_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_U_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_U_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_U_upper")
ELSE()
  ADD_TEST(bsdtar_test_option_U_upper NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_X_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_X_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_X_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_X_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_X_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_X_upper")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_X_upper "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_X_upper")
ELSE()
  ADD_TEST(bsdtar_test_option_X_upper NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_b "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_b")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_b "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_b")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_b "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_b")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_b "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_b")
ELSE()
  ADD_TEST(bsdtar_test_option_b NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_exclude "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_exclude")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_exclude "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_exclude")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_exclude "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_exclude")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_exclude "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_exclude")
ELSE()
  ADD_TEST(bsdtar_test_option_exclude NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_gid_gname "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_gid_gname")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_gid_gname "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_gid_gname")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_gid_gname "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_gid_gname")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_gid_gname "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_gid_gname")
ELSE()
  ADD_TEST(bsdtar_test_option_gid_gname NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_k "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_k")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_k "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_k")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_k "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_k")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_k "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_k")
ELSE()
  ADD_TEST(bsdtar_test_option_k NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_keep_newer_files "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_keep_newer_files")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_keep_newer_files "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_keep_newer_files")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_keep_newer_files "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_keep_newer_files")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_keep_newer_files "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_keep_newer_files")
ELSE()
  ADD_TEST(bsdtar_test_option_keep_newer_files NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_n "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_n")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_n "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_n")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_n "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_n")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_n "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_n")
ELSE()
  ADD_TEST(bsdtar_test_option_n NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_newer_than "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_newer_than")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_newer_than "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_newer_than")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_newer_than "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_newer_than")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_newer_than "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_newer_than")
ELSE()
  ADD_TEST(bsdtar_test_option_newer_than NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_nodump "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_nodump")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_nodump "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_nodump")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_nodump "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_nodump")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_nodump "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_nodump")
ELSE()
  ADD_TEST(bsdtar_test_option_nodump NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_q "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_q")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_q "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_q")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_q "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_q")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_q "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_q")
ELSE()
  ADD_TEST(bsdtar_test_option_q NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_r "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_r")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_r "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_r")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_r "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_r")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_r "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_r")
ELSE()
  ADD_TEST(bsdtar_test_option_r NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_s "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_s")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_s "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_s")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_s "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_s")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_s "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_s")
ELSE()
  ADD_TEST(bsdtar_test_option_s NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_option_uid_uname "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_uid_uname")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_option_uid_uname "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_uid_uname")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_option_uid_uname "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_uid_uname")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_option_uid_uname "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_option_uid_uname")
ELSE()
  ADD_TEST(bsdtar_test_option_uid_uname NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_patterns "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_patterns")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_patterns "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_patterns")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_patterns "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_patterns")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_patterns "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_patterns")
ELSE()
  ADD_TEST(bsdtar_test_patterns NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_print_longpath "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_print_longpath")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_print_longpath "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_print_longpath")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_print_longpath "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_print_longpath")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_print_longpath "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_print_longpath")
ELSE()
  ADD_TEST(bsdtar_test_print_longpath NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_stdio "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_stdio")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_stdio "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_stdio")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_stdio "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_stdio")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_stdio "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_stdio")
ELSE()
  ADD_TEST(bsdtar_test_stdio NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_strip_components "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_strip_components")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_strip_components "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_strip_components")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_strip_components "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_strip_components")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_strip_components "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_strip_components")
ELSE()
  ADD_TEST(bsdtar_test_strip_components NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_symlink_dir "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_symlink_dir")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_symlink_dir "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_symlink_dir")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_symlink_dir "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_symlink_dir")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_symlink_dir "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_symlink_dir")
ELSE()
  ADD_TEST(bsdtar_test_symlink_dir NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_version "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_version")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_version "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_version")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_version "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_version")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_version "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_version")
ELSE()
  ADD_TEST(bsdtar_test_version NOT_AVAILABLE)
ENDIF()
IF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  ADD_TEST(bsdtar_test_windows "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Debug/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_windows")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  ADD_TEST(bsdtar_test_windows "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/Release/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_windows")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  ADD_TEST(bsdtar_test_windows "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/MinSizeRel/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_windows")
ELSEIF("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  ADD_TEST(bsdtar_test_windows "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar_test.exe" "-vv" "-p" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/bin/RelWithDebInfo/bsdtar.exe" "-r" "E:/llvm/libarchive-3.0.4/libarchive-3.0.4/tar/test" "test_windows")
ELSE()
  ADD_TEST(bsdtar_test_windows NOT_AVAILABLE)
ENDIF()
